// constants.js

export const LAYERS = {
  one: {
    circle: true,
    pieces: [
      {
        top: "18%",
        right: "15%",
        width: 120,
        height: 30,
        color: "button-bg",
        direction: "right",
        delay: 0.5,
        distance: 120,
        duration: 8,
      },
      {
        top: "45%",
        left: "15%",
        width: 150,
        height: 50,
        color: "button-bg",
        direction: "left",
        delay: 1,
        distance: 120,
        duration: 8,
      },
      {
        top: "75%",
        left: "10%",
        width: 70,
        height: 20,
        color: "button-bg",
        direction: "left",
        delay: 1.5,
        distance: 120,
        duration: 8,
      },
    ],
  },

  two: {
    pieces: [
      {
        top: "25%",
        left: "0%",
        width: 120,
        height: 40,
        color: "active-bar",
        direction: "left",
        delay: 2,
        distance: 120,
        duration: 8,
      },
      {
        top: "35%",
        right: "15%",
        width: 180,
        height: 50,
        color: "active-bar",
        direction: "right",
        delay: 2.5,
        distance: 120,
        duration: 8,
      },
      {
        top: "80%",
        right: "10%",
        width: 160,
        height: 20,
        color: "active-bar",
        direction: "right",
        delay: 3,
        distance: 120,
        duration: 8,
      },
    ],
  },

  three: {
    pieces: [
      {
        top: "35%",
        left: "25%",
        width: 80,
        height: 20,
        color: "bg-primary",
        direction: "left",
        delay: 3.5,
        distance: 120,
        duration: 8,
      },
      {
        top: "55%",
        right: "10%",
        width: 140,
        height: 40,
        color: "bg-primary",
        direction: "right",
        delay: 4,
        distance: 120,
        duration: 8,
      },
      {
        top: "68%",
        left: "40%",
        width: 80,
        height: 20,
        color: "bg-primary",
        direction: "left",
        delay: 4.5,
        distance: 120,
        duration: 8,
      },
    ],
  },
};
